### ISSUE TITLE
Server crash, "Unable to construct this menu by type"

### ISSUE THREAD

**Issue by Flarkinater** [EnvyWare/PixelHuntRemastered#14]
Hunts version: 3.2.1 (currently latest)
Crash log: https://pastebin.com/paEYkALT

I've only had this crash twice, but they were both within the last 2 days, on the same version. It appears both crashes happened when a player did /hunt. In one case, I was able to see in the logs that a player successfully ran /hunt, then the server crashed when they ran in again 2 minutes later. The hunts were not re-rolled during this time, so the crash is seemingly unrelated to the specific Pokemon sprites in the GUI

**Comment by danorris709** [comment]
Fixed in upcoming version
